# Generated by Django 4.2.7 on 2025-09-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_type',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
    ]
